#ifndef _ERROR_H
#define _ERROR_H

#define CRABDB_ERROR_UNKNOWN            10000
#define CRABDB_ERROR_IO	                10001
#define CRABDB_ERROR_DATA_CORRUPTION   	10002
#define CRABDB_ERROR_INVALID_ARGUMENT   10003
#define CRABDB_ERROR_NO_SUCH_BUCKET     10004
#define CRABDB_ERROR_NO_SUCH_TABLE      10005
#define CRABDB_ERROR_NO_SUCH_FIELD      10006
#define CRABDB_ERROR_NOT_MASTER         10007
#define CRABDB_ERROR_COMPILER_FAILURE   10008

#define CRABDB_ERROR_CREATE_BUCKET      10009
#define CRABDB_ERROR_INSERT_TABLE       10010

#endif
